// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAENviL9UVeRgBvYBuaGs6r5mwhW8YAoU0',
    appId: '1:54489289056:web:575c3f19c0246a10784e05',
    messagingSenderId: '54489289056',
    projectId: 'todolist-e7a84',
    authDomain: 'todolist-e7a84.firebaseapp.com',
    storageBucket: 'todolist-e7a84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl9lqI-6FdbD5IYWspJTceZSQOXy_M-Jk',
    appId: '1:54489289056:android:56096ca192ede602784e05',
    messagingSenderId: '54489289056',
    projectId: 'todolist-e7a84',
    storageBucket: 'todolist-e7a84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXM2s11rpKr-9XIo5ARFmlzMMztbD3Fqo',
    appId: '1:54489289056:ios:1dfe4f251800e7f9784e05',
    messagingSenderId: '54489289056',
    projectId: 'todolist-e7a84',
    storageBucket: 'todolist-e7a84.appspot.com',
    iosClientId: '54489289056-1sh83aok0skqhc5kmmff9pga6umb4nsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXM2s11rpKr-9XIo5ARFmlzMMztbD3Fqo',
    appId: '1:54489289056:ios:1dfe4f251800e7f9784e05',
    messagingSenderId: '54489289056',
    projectId: 'todolist-e7a84',
    storageBucket: 'todolist-e7a84.appspot.com',
    iosClientId: '54489289056-1sh83aok0skqhc5kmmff9pga6umb4nsl.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );
}
